/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiyi_engine_engine */

#ifndef _Included_com_qiyi_engine_engine
#define _Included_com_qiyi_engine_engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiyi_engine_engine
 * Method:    native_GetVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_qiyi_engine_engine_native_1GetVersion
  (JNIEnv *, jobject);


JNIEXPORT jlong JNICALL Java_com_qiyi_engine_engine_native_1initialize
        (JNIEnv *, jclass, jobject);
#ifdef __cplusplus
}
#endif
#endif
